namespace AccpacGraphqlClean.Domain;

public sealed class AROpenInvoices
{
    public string? Compid { get; set; }
    public string? CustomerCode { get; set; }
    public List<AROpenDocument> Document { get; set; } = new();
}

public sealed class AROpenDocument
{
    public string? CustomerNumber000 { get; set; }
    public string? DocumentNumber001 { get; set; }
    public string? CheckReceiptNo002 { get; set; }
    public string? OrderNumber003 { get; set; }
    public string? PONumber004 { get; set; }
    public DateTime? DueDate005 { get; set; }
    public string? NationalAccountNumber006 { get; set; }
    public string? ShipToLocation007 { get; set; }
    public string? TransactionType008 { get; set; }
    public string? DocumentType009 { get; set; }
    public DateTime? BatchDate010 { get; set; }
    public string? BatchNumber011 { get; set; }
    public string? EntryNumber012 { get; set; }
    public string? GroupCode013 { get; set; }
    public string? DocumentDescription014 { get; set; }
    public DateTime? DocumentDate015 { get; set; }
    public DateTime? AsofDate016 { get; set; }
    public string? Terms017 { get; set; }
    public DateTime? DiscountDate018 { get; set; }
    public string? CurrencyCode019 { get; set; }
    public string? RateType020 { get; set; }
    public string? RateOverridden021 { get; set; }
    public string? ExchangeRate022 { get; set; }
    public string? FuncCurrencyInvoiceAmount023 { get; set; }
    public string? FuncCurrencyAmountDue024 { get; set; }
    public string? FuncCurrencyTaxableAmount025 { get; set; }
    public string? FuncCurrencyNonTaxableAmt026 { get; set; }
    public string? FuncCurrencyTaxAmount027 { get; set; }
    public string? FuncCurrencyDiscountAmount028 { get; set; }
    public string? CustCurrencyInvoiceAmount029 { get; set; }
    public string? CustCurrencyAmountDue030 { get; set; }
    public string? CustCurrencyTaxableAmount031 { get; set; }
    public string? CustCurrencyNonTaxableAmt032 { get; set; }
    public string? CustCurrencyTaxAmount033 { get; set; }
    public string? CustCurrencyDiscountAmount034 { get; set; }
    public string? FullyPaid035 { get; set; }
    public DateTime? LastActivityDate036 { get; set; }
    public DateTime? LastStatementDate037 { get; set; }
    public string? NumberofScheduledPayments040 { get; set; }
    public string? ReservedLastPaymentNumberP041 { get; set; }
    public string? PaymentNumberonLastStatement042 { get; set; }
    public string? ReservedReceiptAmount043 { get; set; }
    public string? LastAppliedPaymentSeqNo044 { get; set; }
    public string? DoNotCalcTax045 { get; set; }
    public string? TaxAuthority1046 { get; set; }
    public string? TaxAuthority2047 { get; set; }
    public string? TaxAuthority3048 { get; set; }
    public string? TaxAuthority4049 { get; set; }
    public string? TaxAuthority5050 { get; set; }
    public string? FuncBaseAmount1051 { get; set; }
    public string? FuncBaseAmount2052 { get; set; }
    public string? FuncBaseAmount3053 { get; set; }
    public string? FuncBaseAmount4054 { get; set; }
    public string? FuncBaseAmount5055 { get; set; }
    public string? FuncTaxAmount1056 { get; set; }
    public string? FuncTaxAmount2057 { get; set; }
    public string? FuncTaxAmount3058 { get; set; }
    public string? FuncTaxAmount4059 { get; set; }
    public string? FuncTaxAmount5060 { get; set; }
    public string? CustBaseAmount1061 { get; set; }
    public string? CustBaseAmount2062 { get; set; }
    public string? CustBaseAmount3063 { get; set; }
    public string? CustBaseAmount4064 { get; set; }
    public string? CustBaseAmount5065 { get; set; }
    public string? CustTaxAmount1066 { get; set; }
    public string? CustTaxAmount2067 { get; set; }
    public string? CustTaxAmount3068 { get; set; }
    public string? CustTaxAmount4069 { get; set; }
    public string? CustTaxAmount5070 { get; set; }
    public string? Salesperson1071 { get; set; }
    public string? Salesperson2072 { get; set; }
    public string? Salesperson3073 { get; set; }
    public string? Salesperson4074 { get; set; }
    public string? Salesperson5075 { get; set; }
    public string? SalesSplitPercentage1076 { get; set; }
    public string? SalesSplitPercentage2077 { get; set; }
    public string? SalesSplitPercentage3078 { get; set; }
    public string? SalesSplitPercentage4079 { get; set; }
    public string? SalesSplitPercentage5080 { get; set; }
    public string? FiscalYear081 { get; set; }
    public string? FiscalPeriod082 { get; set; }
    public string? PrepayApplytoDocNo083 { get; set; }
    public DateTime? PostingDate084 { get; set; }
    public DateTime? RateDate085 { get; set; }
    public string? RateOperator086 { get; set; }
    public string? LastActivityYearPeriod087 { get; set; }
    public string? BankCode088 { get; set; }
    public string? DepositNumber089 { get; set; }
    public string? PostingSequenceNo090 { get; set; }
    public string? JobRelated091 { get; set; }
    public string? HasRetainage092 { get; set; }
    public string? RetainageOutstanding093 { get; set; }
    public DateTime? DateRetainageDue094 { get; set; }
    public string? FuncCurrOrigRtngAmt095 { get; set; }
    public string? FuncCurrRetainageAmount096 { get; set; }
    public string? CustCurrOrigRtngAmt097 { get; set; }
    public string? CustCurrRetainageAmount098 { get; set; }
    public string? RetainageTermsCode099 { get; set; }
    public string? RetainageExchangeRate100 { get; set; }
    public string? OriginalDocNo101 { get; set; }
    public string? OptionalFields102 { get; set; }
    public string? SourceApplication103 { get; set; }
    public string? ARVersionCreatedIn104 { get; set; }
    public string? InvoiceType105 { get; set; }
    public string? DepositSerialNumber106 { get; set; }
    public string? DepositLineNumber107 { get; set; }
    public string? BatchType108 { get; set; }
    public string? NumberofOBLJDetails109 { get; set; }
    public string? TaxReportingCurrencyCode110 { get; set; }
    public string? TaxReportingExchangeRate111 { get; set; }
    public string? TaxReportingRateType112 { get; set; }
    public DateTime? TaxReportingRateDate113 { get; set; }
    public string? TaxReportingRateOperator114 { get; set; }
    public string? TaxReportingRateOverride115 { get; set; }
    public string? ReportRetainageTax116 { get; set; }
    public string? TaxGroup117 { get; set; }
    public string? TaxStateVersion118 { get; set; }
    public string? TaxReportingCalculateMethod119 { get; set; }
    public string? TaxClass1120 { get; set; }
    public string? TaxClass2121 { get; set; }
    public string? TaxClass3122 { get; set; }
    public string? TaxClass4123 { get; set; }
    public string? TaxClass5124 { get; set; }
    public string? TaxBase1125 { get; set; }
    public string? TaxBase2126 { get; set; }
    public string? TaxBase3127 { get; set; }
    public string? TaxBase4128 { get; set; }
    public string? TaxBase5129 { get; set; }
    public string? TaxAmount1130 { get; set; }
    public string? TaxAmount2131 { get; set; }
    public string? TaxAmount3132 { get; set; }
    public string? TaxAmount4133 { get; set; }
    public string? TaxAmount5134 { get; set; }
    public string? ShipmentNumber135 { get; set; }
    public DateTime? EarliestBackdatedActivityDate136 { get; set; }
    public DateTime? LastRevaluationDate137 { get; set; }
    public string? OrigExchangeRate138 { get; set; }
    public string? OrigRateType139 { get; set; }
    public DateTime? OrigRateDate140 { get; set; }
    public string? OrigRateOperator141 { get; set; }
    public string? OrigRateOverrideFlag142 { get; set; }
    public string? AccountSet143 { get; set; }
    public DateTime? DatePaid144 { get; set; }
    public string? MiscReceiptFlag145 { get; set; }
    public string? TerritotyCode146 { get; set; }
}

public sealed class ARAgedAnalysis
{
    public string? Compid { get; set; }

    public string? CommandCode000 { get; set; }
    public string? CustomerNumber001 { get; set; }
    public DateTime? PostingDate002 { get; set; }
    public string? DocumentNumber003 { get; set; }
    public string? CheckReceiptNo004 { get; set; }
    public string? DocumentType005 { get; set; }
    public string? TransactionType006 { get; set; }
    public string? AmountDueSource007 { get; set; }
    public string? AmountDueFunctional008 { get; set; }
    public DateTime? StartingInvoiceDate009 { get; set; }
    public DateTime? DueDate010 { get; set; }
    public DateTime? AgeasofDate011 { get; set; }
    public DateTime? CutoffDate012 { get; set; }
    public string? Ageby013 { get; set; }
    public string? AgeFullyPaidDocuments014 { get; set; }
    public string? IncludeZeroBalances015 { get; set; }
    public string? ReportType016 { get; set; }
    public string? Current017 { get; set; }
    public string? FirstPeriod018 { get; set; }
    public string? SecondPeriod019 { get; set; }
    public string? ThirdPeriod020 { get; set; }
    public string? FourthPeriod021 { get; set; }
    public string? FirstForwardPeriod022 { get; set; }
    public string? SecondForwardPeriod023 { get; set; }
    public string? ThirdForwardPeriod024 { get; set; }
    public string? FourthForwardPeriod025 { get; set; }
    public string? IncludeOverCreditLimit026 { get; set; }
    public string? Range1From027 { get; set; }
    public string? Range1To028 { get; set; }
    public string? Range1Type029 { get; set; }
    public string? Range2From030 { get; set; }
    public string? Range2To031 { get; set; }
    public string? Range2Type032 { get; set; }
    public string? Range3From033 { get; set; }
    public string? Range3To034 { get; set; }
    public string? Range3Type035 { get; set; }
    public string? Range4From036 { get; set; }
    public string? Range4To037 { get; set; }
    public string? Range4Type038 { get; set; }
    public string? NumberofDaysOutstandingFrom039 { get; set; }
    public string? NumberofDaysOutstandingTo040 { get; set; }
    public string? CurrentAmountDueSource041 { get; set; }
    public string? CurrentAmountDueFunctional042 { get; set; }
    public DateTime? CurrentDate043 { get; set; }
    public string? Period1AmountDueSource044 { get; set; }
    public string? Period1AmountDueFunctional045 { get; set; }
    public DateTime? Period1Date046 { get; set; }
    public string? Period2AmountDueSource047 { get; set; }
    public string? Period2AmountDueFunctional048 { get; set; }
    public DateTime? Period2Date049 { get; set; }
    public string? Period3AmountDueSource050 { get; set; }
    public string? Period3AmountDueFunctional051 { get; set; }
    public DateTime? Period3Date052 { get; set; }
    public string? Period4AmountDueSource053 { get; set; }
    public string? Period4AmountDueFunctional054 { get; set; }
    public DateTime? Period4Date055 { get; set; }
    public string? Period5AmountDueSource056 { get; set; }
    public string? Period5AmountDueFunctional057 { get; set; }
    public DateTime? Period5Date058 { get; set; }
    public string? Period6AmountDueSource059 { get; set; }
    public string? Period6AmountDueFunctional060 { get; set; }
    public DateTime? Period6Date061 { get; set; }
    public string? Period7AmountDueSource062 { get; set; }
    public string? Period7AmountDueFunctional063 { get; set; }
    public DateTime? Period7Date064 { get; set; }
    public string? Period8AmountDueSource065 { get; set; }
    public string? Period8AmountDueFunctional066 { get; set; }
    public DateTime? Period8Date067 { get; set; }
    public string? PeriodOpenItemScheduleDue068 { get; set; }
    public string? TotalBackwardAgingSource069 { get; set; }
    public string? TotalBackwardAgingFunctional070 { get; set; }
    public string? TotalForwardAgingSource071 { get; set; }
    public string? TotalForwardAgingFunctional072 { get; set; }
    public string? DisplayMeter073 { get; set; }
    public string? IncludeAppliedDetails074 { get; set; }
    public string? CustomerAccountType075 { get; set; }
    public string? CutoffBy076 { get; set; }
    public string? CutoffYear077 { get; set; }
    public string? CutoffPeriod078 { get; set; }
    public string? FieldName1079 { get; set; }
    public string? FieldName2080 { get; set; }
    public string? FieldName3081 { get; set; }
    public string? FieldName4082 { get; set; }
    public string? IncludePrepayment083 { get; set; }
    public string? SortFieldIndex1085 { get; set; }
    public string? SortFieldIndex2086 { get; set; }
    public string? SortFieldIndex3087 { get; set; }
    public string? SortFieldIndex4088 { get; set; }
    public string? SortFieldName1089 { get; set; }
    public string? SortFieldName2090 { get; set; }
    public string? SortFieldName3091 { get; set; }
    public string? SortFieldName4092 { get; set; }
    public string? IncludeInvoice093 { get; set; }
    public string? IncludeDebitNote094 { get; set; }
    public string? IncludeCreditNote095 { get; set; }
    public string? IncludeInterest096 { get; set; }
    public string? IncludeUnappliedCash097 { get; set; }
    public string? IncludeReceipt098 { get; set; }
    public string? IncludeRefund099 { get; set; }
    public string? IncludeAdjustment100 { get; set; }
    public DateTime? FromDate101 { get; set; }
    public string? FromYear102 { get; set; }
    public string? FromPeriod103 { get; set; }
    public string? ShowAgedRetainage104 { get; set; }
}
